// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmqopmscyahntvbhtbez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtcW9wbXNjeWFobnR2Ymh0YmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDM5OTAsImV4cCI6MjA2NTI3OTk5MH0.U4mlwNHA9w6dR8BTjrAB5seO3ifbRxs76fwdGOHCWAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);